// font
import { Roboto, Roboto_Mono } from "next/font/google";

// css
import "./globals.css";

// components
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"

// font
const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "smart city insights",
  description: "Generated by create next app",
};


export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        {/* sidebar */}
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
        {/* end of sidebar */}
      </body>
    </html>
  );
}
